global using HDF.PInvoke;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using System.Runtime.InteropServices;
global using System.Text;
global using herr_t = System.Int32;
global using htri_t = System.Int32;
global using hid_t = System.Int64;
global using size_t = System.IntPtr;
global using ssize_t = System.IntPtr;
global using hbool_t = System.UInt32;
global using hsize_t = System.UInt64;
global using haddr_t = System.UInt64;
